# Generated by Django 3.1.7 on 2021-03-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='updated_at',
        ),
    ]
